### ISSUE TITLE
Building 4.7.5 From Source Fails with Incompatible Pointer Type

### ISSUE THREAD

**Issue by pixel1138** [wazuh/wazuh-agent#3] opened 2024-06-01 19:36 UTC
Trying to build wazuh-agent 4.7.5 from source using ./install.sh results in a build failure with the below error:

```
client-agent/receiver.c: In function ‘receive_msg’:
client-agent/receiver.c:280:81: error: passing argument 4 of ‘UnmergeFiles’ from incompatible pointer type [-Wincompatible-pointer-types]
  280 |                                 if (!UnmergeFiles(file, SHAREDCFG_DIR, OS_TEXT, &ignore_list)) {
      |                                                                                 ^~~~~~~~~~~~
      |                                                                                 |
      |                                                                                 char ***
In file included from ./headers/shared.h:256,
                 from client-agent/receiver.c:11:
./headers/file_op.h:221:85: note: expected ‘const char ***’ but argument is of type ‘char ***’
  221 | int UnmergeFiles(const char *finalpath, const char *optdir, int mode, const char ***unmerged_files) __attribute__((nonnull(1)));
      |                                                                       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
client-agent/receiver.c:287:72: error: passing argument 2 of ‘cldir_ex_ignore’ from incompatible pointer type [-Wincompatible-pointer-types]
  287 |                                     if (cldir_ex_ignore(SHAREDCFG_DIR, ignore_list)) {
      |                                                                        ^~~~~~~~~~~
      |                                                                        |
      |                                                                        char **
./headers/file_op.h:346:54: note: expected ‘const char **’ but argument is of type ‘char **’
  346 | int cldir_ex_ignore(const char * name, const char ** ignore);
      |                                        ~~~~~~~~~~~~~~^~~~~~
make[1]: *** [Makefile:1934: client-agent/receiver.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/chris/Downloads/wazuh-4.7.5/src'
make: *** [Makefile:814: agent] Error 2

 Error 0x5.
 Building error. Unable to finish the installation.
```

**Comment by vikman90** [comment] 2024-06-06 13:08
@pixel1138 this issue seems to be a duplicate of:

- https://github.com/wazuh/wazuh/issues/23568

The fix will apply as of version 4.9.0.

Thanks.

**Closed by vikman90** 2024-06-06 13:08 UTC
Labels: reporter/community, request/operational
